import { MCSuper } from '../MCSuper';
import { Rectangle } from '../../geom/rectangle';
import { Point } from '../../geom/point';
import { MovieClipData } from "./MovieClipData";
import { SimpleRect } from '../../geom/SimpleRect';

/**
 * @version: 1.0
 * @Author: Wayne Yu
 * @LastEditTime: 2021-12-24 16:02:25
 * @description: Movie clip, you can play sequence frame animation through movie clip.
 * @ 影片剪辑，可以通过影片剪辑播放序列帧动画。
 */
export class MovieClip extends MCSuper{

    private mcData: MovieClipData;

    private labels!: any[];
    private defaultFrames!: Array<any>;

    get textruePic(): string{
        return this.mcData?.texture;
    }

    anchorOffsetChange: Function | null = null;

    anchorOffset: Point = new Point;

    /**
     * Creates an instance of MovieClip.
     * @param {MovieClipData} mcData must create by MovieClipDataFactory
     * @memberof MovieClip
     * @description: When creating MovieClip, you need to use the "getMovieClipData" method of the "movieclipdatafactory" class. The material required to create movieclipdatafactory can be generated by the "texture merge" tool.
     * @ 创建MovieClip时，需要使用MovieClipDataFactory类的getMovieClipData方法。创建MovieClipDataFactory所需要的素材，可用"Texture Merger"工具生成。
     */
    constructor( mcData: MovieClipData ){
        super();
        this.mcData = mcData;
        this.waitForAssets();
    }

    dispose(){
        super.dispose();
        this.anchorOffsetChange = null;
    }

    private waitForAssets(){
        if( this.mcData.mc ){
            this.frameRate = this.mcData.mc.frameRate;
            this.labels = this.mcData.mc.labels;
            this.defaultFrames = this.frames = [];
            let res: any = this.mcData.res;
            for( let i: number = 0; i < this.mcData.mc.frames.length; i++ ){
                let frameInfo: any = this.mcData.mc.frames[i];
                frameInfo.position = new Point().init( frameInfo.x, frameInfo.y );
                let rect: SimpleRect = res[frameInfo.res];
                frameInfo.rect = new Rectangle().init(rect.x,rect.y,rect.w,rect.h);
                let count: number = frameInfo.duration;
                if( !count ) count = 1;
                while( count-- > 0 ){
                    this.frames.push( frameInfo );
                }
            }

            this.startAfterAssetsGot();
        }
        else setTimeout( this.waitForAssets.bind( this ), 50 );
    }

    /**
     * @param {*} frameOrLabel
     * @param {number} [times=-1]
     * @return {*} 
     * @memberof MovieClip
     * @description: Starts playing the SWF file at the specified frame.
     * @ 从指定帧开始播放动画。
     */
    gotoAndPlay( frameOrLabel: any, times: number = -1 ){
        if( !this.frames ){
            setTimeout( this.gotoAndPlay.bind( this ), 35, frameOrLabel, times );
            return;
        }
        this.playTimes = times;

        if( typeof frameOrLabel=='string' ){
            let labelData: any[] | null = this.getLabelFrames(frameOrLabel);
            if( labelData ){
                this.frames = labelData;
                this.gotoAndPlayByNumber( 1 );
            }
            else console.error( "frame label error" );
        }
        else this.gotoAndPlayByNumber( frameOrLabel );
    }

    /**
     * @param {(string | number)} frameOrLabel
     * @return {*} 
     * @memberof MovieClip
     * @description: Brings the playhead to the specified frame of the movie clip and stops it there.
     * @ 将播放头移到影片剪辑的指定帧并停在那里。
     */
    gotoAndStop( frameOrLabel: string | number ){
        if( !this.frames ){
            setTimeout( this.gotoAndStop.bind( this ), 35, frameOrLabel );
            return;
        }

        if( typeof frameOrLabel=='string' ){
            let labelData: any[] | null = this.getLabelFrames(frameOrLabel);
            if( labelData ){
                this.frames = labelData;
                this.gotoAndStopByNumber( 1 );
            }
            else console.error( "frame label error" );
        }
        else this.gotoAndStopByNumber( frameOrLabel );
    }

    /**
     * @param {number} offsetX
     * @param {number} offsetY
     * @memberof MovieClip
     * @description: Sets the anchor of the object
     * @ 设置对象的锚点
     */
    setAnchorOffset( offsetX: number, offsetY: number ){
        this.anchorOffset = new Point().init( offsetX, offsetY );
        if( this.anchorOffsetChange ) this.anchorOffsetChange();
    }

    private getLabelFrames( label: string ): any[] | null{
        let labelObj: any;
        if( this.labels && this.labels.length ){
            for( let i: number = 0; i < this.labels.length; i++ ){
                if( this.labels[i].name == label ){
                    labelObj = this.labels[i];
                    break;
                }
            }
        }
        else return null;

        if( !labelObj ) return null;

        let allFrames: any[] = [];
        let curruntFrame: number = 0;
        let frames: any[] = [];
        for( let i: number = 0; i < this.defaultFrames.length; i++ ){
            if( allFrames.indexOf( this.defaultFrames[i] ) < 0 ){
                curruntFrame++;
                allFrames.push( this.defaultFrames[i] )
            }
            if( curruntFrame >= labelObj.frame ){
                frames.push( this.defaultFrames[i] );
                if( curruntFrame == labelObj.end ) break;
            }
        }
        return frames;
    }
}
